### Create user
POST http://localhost:9000/dagacube-service/v1/dagacubeService
Content-Type: application/json

{
  "username": "Lloyd",
  "balance": 100
}


### Get balance
GET http://localhost:9000/dagacube-service/v1/dagacubeService/1/balance


### Wager
POST http://localhost:9000/dagacube-service/v1/dagacubeService/wager
Content-Type: application/json
TransactionId: txn1

{
  "playerId": "1",
  "amount": 50,
  "promoCode": "paper"
}


### Win
POST http://localhost:9000/dagacube-service/v1/dagacubeService/win
Content-Type: application/json
TransactionId: txn3

{
  "playerId": "1",
  "amount": 50
}


### player transaction history. Enter you super secret password in the body below
POST http://localhost:9000/dagacube-service/v1/dagacubeService/transactions
Content-Type: application/json

{
  "username": "Lloyd",
  "password": "swordfish"
}

