### Create user
POST http://localhost:9000/dagacube-service/v1/dagacubeService
Content-Type: application/json
cookie: a;lskdjf;alsdjkf;lakjdfaldkjflsadjf

{
  "username": "Lloyd",
  "balance": 100
}


### Get balance
GET http://localhost:9000/dagacube-service/v1/dagacubeService/1/balance


### Wager
POST http://localhost:9000/dagacube-service/v1/dagacubeService/1/wager/50
Transactionid: txnid1


### Win
POST http://localhost:9000/dagacube-service/v1/dagacubeService/1/win/50
Transactionid: txnid2


### player transaction history. Enter you super secret password in the body below
POST http://localhost:9000/dagacube-service/v1/dagacubeService/transactions
Content-Type: application/json

{
  "username": "Lloyd",
  "password": ""
}

