DROP TABLE IF EXISTS DAGACUBE_SYSTEM_USER ;

CREATE TABLE DAGACUBE_SYSTEM_USER
(
   id         INT AUTO_INCREMENT PRIMARY KEY,
   username   VARCHAR(256) NOT NULL,
   password   VARCHAR(256) NOT NULL
);
